Vagrant.configure("2") do |config|
  # config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/focal/current/focal-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "generic/ubuntu2204"
  # config.vm.box_version = "20211020.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096  # Set memory to 4GB
    vb.cpus = 2         # Set CPU to use 2 cores
  end
end